Controllers/MaterialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Company.Data;
using Company.Models.BusinessLogic;
using Microsoft.AspNetCore.Authorization;

namespace Company.Controllers
{
    [Authorize(Roles="Администратор")]
    public class MaterialsController : Controller
    {
        private readonly CompanyContext _context;

        public MaterialsController(CompanyContext context)
        {
            _context = context;
        }

        // GET: Materials
        public async Task<IActionResult> Index()
        {
            return View(await _context.Materials.ToListAsync());
        }

        // GET: Materials/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Material material)
        {
            if (ModelState.IsValid)
            {
                _context.Add(material);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(material);
        }

        // GET: Materials/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.Materials
                .SingleOrDefaultAsync(m => m.Id == id);
            if (material == null)
            {
                return NotFound();
            }

            return View(material);
        }

        // POST: Materials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var material = await _context.Materials.SingleOrDefaultAsync(m => m.Id == id);
            _context.Materials.Remove(material);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaterialExists(int id)
        {
            return _context.Materials.Any(e => e.Id == id);
        }
    }
}

Controllers/ObjectOfExpendituresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Company.Data;
using Company.Models.BusinessLogic;
using Microsoft.AspNetCore.Identity;
using Company.Models;
using Microsoft.AspNetCore.Authorization;

namespace Company.Controllers
{
    public class ObjectOfExpendituresController : Controller
    {
        private readonly CompanyContext _context;

        public ObjectOfExpendituresController(CompanyContext context)
        {
            _context = context;

        }

        // GET: ObjectOfExpenditures
        public async Task<IActionResult> Index()
        {
            var companyContext = _context.ObjectOfExpenditures.Include(o => o.Material).Include(o => o.Provider);
            return View(await companyContext.ToListAsync());
        }
        [Authorize(Roles = "Менеджер")]
        public async Task<IActionResult> CountlyMonth(string dateFrom,string dateTo,string material, string provider)
        {
            var materials = from ObjectOfExpenditure in _context.ObjectOfExpenditures select ObjectOfExpenditure;

            if (!String.IsNullOrEmpty(dateFrom) && !String.IsNullOrEmpty(dateTo))
            {

                materials = materials.Where(s => s.Date.CompareTo(dateFrom) >= 0 && s.Date.CompareTo(dateTo) <= 0);
            }
            if (!String.IsNullOrEmpty(material))
            {
                materials = materials.Where(s => s.Material.Name.ToLower().Contains(material));
            }
            if (!String.IsNullOrEmpty(provider))
            {
                materials = materials.Where(s => s.Provider.Name.ToLower().Contains(provider));
            }

            ViewBag.Materials = await _context.Materials.ToListAsync();

            ViewBag.Providers = await _context.Providers.ToListAsync();
            return View(materials);
        }
        // GET: ObjectOfExpenditures/Create

        [Authorize(Roles = "Учётчик")]
        public IActionResult Create()
        {
            ViewData["MaterialId"] = new SelectList(_context.Materials, "Id", "Name");
            ViewData["ProviderId"] = new SelectList(_context.Providers, "Id", "Name");
            return View();
        }

        [Authorize(Roles = "Учётчик")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MaterialId,Amount,ProviderId")] ObjectOfExpenditure objectOfExpenditure)
        {
            objectOfExpenditure.Date = DateTime.Now;
            objectOfExpenditure.UserId = User.Identity.Name;
            if (ModelState.IsValid)
            {
                _context.Add(objectOfExpenditure);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaterialId"] = new SelectList(_context.Materials, "Id", "Name", objectOfExpenditure.MaterialId);
            ViewData["ProviderId"] = new SelectList(_context.Providers, "Id", "Name", objectOfExpenditure.ProviderId);
            return View(objectOfExpenditure);
        }

        [Authorize(Roles = "Менеджер")]
        // GET: ObjectOfExpenditures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objectOfExpenditure = await _context.ObjectOfExpenditures
                .Include(o => o.Material)
                .Include(o => o.Provider)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (objectOfExpenditure == null)
            {
                return NotFound();
            }

            return View(objectOfExpenditure);
        }

        // POST: ObjectOfExpenditures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var objectOfExpenditure = await _context.ObjectOfExpenditures.SingleOrDefaultAsync(m => m.Id == id);
            _context.ObjectOfExpenditures.Remove(objectOfExpenditure);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ObjectOfExpenditureExists(int id)
        {
            return _context.ObjectOfExpenditures.Any(e => e.Id == id);
        }
    }
}

Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Company.Data;
using Company.Models.BusinessLogic;
using Microsoft.AspNetCore.Authorization;

namespace Company.Controllers
{
    [Authorize(Roles = "Администратор")]
    public class ProvidersController : Controller
    {
        private readonly CompanyContext _context;

        public ProvidersController(CompanyContext context)
        {
            _context = context;
        }

        // GET: Providers
        public async Task<IActionResult> Index()
        {
            var companyContext = _context.Providers.Include(p => p.Material);
            return View(await companyContext.ToListAsync());
        }

        // GET: Providers/Details/5
        // GET: Providers/Create
        public IActionResult Create()
        {
            ViewData["MaterialId"] = new SelectList(_context.Materials, "Id", "Name");
            return View();
        }

        // POST: Providers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,MaterialId")] Provider provider)
        {
            if (ModelState.IsValid)
            {
                _context.Add(provider);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaterialId"] = new SelectList(_context.Materials, "Id", "Name", provider.MaterialId);
            return View(provider);
        }
        // GET: Providers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers
                .Include(p => p.Material)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // POST: Providers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var provider = await _context.Providers.SingleOrDefaultAsync(m => m.Id == id);
            _context.Providers.Remove(provider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProviderExists(int id)
        {
            return _context.Providers.Any(e => e.Id == id);
        }
    }
}

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Company.Models;
using Company.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Company.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());
        
        public IActionResult Create() => View();

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<ActionResult> DeleteUser(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)   
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Views/Shared/_ConvertName.cshtml
@model User
@{  int endIndex = Model.Email.LastIndexOf("@");
<span>@Model.Email.Substring(0,endIndex)</span>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Компания</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header  col-sm-2">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    @if (User.IsInRole("Администратор"))
                    {
                    <a class="navbar-brand">Администратор</a>
                    }   
                    else if (User.IsInRole("Менеджер"))
                    {
                    <a class="navbar-brand">Менеджер</a>
                    }
                    else if (User.IsInRole("Учётчик"))
                    {
                    <a class="navbar-brand">Учётчик</a>
                    }     
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-left">
                    <li class="active"><a asp-controller="ObjectOfExpenditures" asp-action="Index">Табель учёта</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Списки<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Materials" asp-action="Index">Материалы</a></li>
                            <li><a asp-controller="Providers" asp-action="Index">Поставщики</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.IsInRole("Администратор"))
                    {
                        <li><a asp-controller="Roles" asp-action="Index">Управление пользователями</a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a>Привет, @User.Identity.Name</a></li>
                        <li>
                            <a>
                                <form method="post" asp-controller="Account" asp-action="LogOff">
                                    <input type="submit" value="Выход" class="btn btn-xs" />
                                </form>
                            </a>
                        </li>

                    }
                    else
                    {
                        <li><a asp-controller="Account" asp-action="Register"><span class="glyphicon glyphicon-user"></span> Регистрация</a></li>
                        <li><a asp-controller="Account" asp-action="Login"><span class="glyphicon glyphicon-log-in"></span> Войти</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Company</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>