Controllers/DoctorScheduleController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using aspnetapp.Models;

namespace aspnetapp.Controllers
{
    public class DoctorScheduleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PatiendCardController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using aspnetapp.Models;

namespace aspnetapp.Controllers
{
    public class PatientCardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/DoctorSchedule/Index.cshtml
@{ ViewData["Title"] = "Doctor"; }

<script type='text/template' id='scheduletemplate'>
    <div class='container mb-3 mt-3'>
        <div class='clndr-controls row'>
            <h3 class='month col text-left'>
                <%= month %>
                    <%= year %>
            </h3>
            <div class = 'col row justify-content-end'>
                <div class='clndr-control-button clndr-previous-button col btn btn-primary mr-1 ml-1'>назад</div>
                <div class='clndr-control-button clndr-next-button col btn btn-primary mr-1 ml-1'>вперед</div>
            </div>
        </div>
    </div>
    <table class='clndr-table table table-bordered text-center' border='0' cellspacing='0' cellpadding='0'>
        <thead class='thead-light'>
            <tr class='header-days'>
                <% for(var i = 0; i < daysOfTheWeek.length; i++) { %>
                    <th class='header-day'>
                        <%= daysOfTheWeek[i] %>
                    </th>
                    <% } %>
            </tr>
        </thead>
        <tbody>
            <% for(var i = 0; i < numberOfRows; i++){ %>
                <tr>
                    <% for(var j = 0; j < 7; j++){ %>
                        <% var d = j + i * 7; %>
                            <td class='<%= days[d].classes %>'>

                                    <div class='day-contents text-left'>
                                            <span>
                                                <%= days[d].day %>
                                            </span>
                                    </div>

                                    <div class='row day-inf pr-0 text-center'>

                                        <div class='relief-time col pr-0 pl-0'>8:00-19:00</div>
                                        <div class='count col pr-0 pl-0'>8/10</div>

                                    </div>

                            </td>
                            <% } %>
                </tr>
                <% } %>
        </tbody>
    </table>
</script>

<diV class='container'>
    <div id='schedule'></div>

    <table class='patientList table table-sm text-center'>
        <tbody>
            <tr>
                <td>12:00</td>

                <td>Иванов И.В.</td>

                <td class = 'recordActions'>
                   @Html.ActionLink("Просмотр карточки","","PatientCard") | @Html.ActionLink("Занести результаты приема в карточку","","")
                </td>
            </tr>

            <tr>
                <td>12:15</td>

                <td>Петров А.В.</td>

                <td class = 'recordActions'>
                    @Html.ActionLink("Просмотр карточки","","PatientCard") | @Html.ActionLink("Занести результаты приема в карточку","","")
                </td>
            </tr>
        </tbody>
    </table>

    @section Styles {
         <link rel='stylesheet' href='~/css/Doctor/main.css' asp-append-version='true' />
     } 
    @section Scripts {

    <script src='https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'></script>

    <script src='/lib/moment/min/moment-with-locales.min.js' asp-append-version='true'></script>

    <script src='/lib/clndr/src/clndr.js' asp-append-version='true'></script>

    <script src='/js/Doctor/main.js' asp-append-version='true'></script>

    }

</div>